import type { Metadata } from "next";
import { Sacramento, Alice, Josefin_Sans } from "next/font/google";
import "./globals.css";
import GradientBackground from "@/components/GradientBackground";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const sacramento = Sacramento({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-display',
})
const alice = Alice({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-serif',
})

const josefinSans = Josefin_Sans({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: "jellablue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sacramento.variable} ${alice.variable} ${josefinSans.variable} h-full antialiased`}
    >
      <body>
        <GradientBackground />
        <div className="min-h-screen px-2 py-2 md:px-6 md:py-4">
          <div className="relative min-h-[calc(100vh-2rem)] md:min-h-[calc(100vh-3rem)] w-full rounded-2xl md:rounded-3xl bg-main shadow-2xl overflow-hidden ">
            <Navbar />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
